// export const products = [
//     { name: 'Ankara', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Wears', id: '001', image: '/images/1.jpg', price: '450.00', available_quantity: 6 },
//     { name: 'Beans', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Food', id: '002', image: '/images/2.jpg', price: '30.60', available_quantity: 7 },
//     { name: 'Shirt', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Wears', id: '003', image: '/images/3.jpg', price: '120.80', available_quantity: 10 },
//     { name: 'Rice', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Food', id: '004', image: '/images/4.jpg', price: '9.00', available_quantity: 40 },
//     { name: 'Ankara', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Wears', id: '005', image: '/images/5.jpg', price: '15.00', available_quantity: 16 },
//     { name: 'Beans', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Food', id: '006', image: '/images/6.jpg', price: '30.60', available_quantity: 8 },
//     { name: 'Shirt', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Wears', id: '007', image: '/images/7.jpg', price: '120.80', available_quantity: 94 },
//     { name: 'Rice', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Food', id: '008', image: '/images/8.jpg', price: '9.00', available_quantity: 45 },
//     { name: 'Ankara', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud', category: 'Wears', id: '009', image: '/images/9.jpg', price: '15.00', available_quantity: 3 }
// ]